### ISSUE TITLE
Gnome 3.20 support

### ISSUE THREAD

**Issue by watermelonjuice** [zpydr/gnome-shell-extension-taskbar#105]
This extension isn't compatible with Gnome 3.20 yet.

**Comment by tobimensch** [comment]
Try to get an error message if you can. For example on my system I can find errors with like "journalctl -xe".

**Comment by Taijian** [comment]
For me, there is not even a system error message. Gnome 3.20 simply disables the extension - both in the control center and on extensions.gnome.org - and does not even try to run it. Gnome says: "This extension is not compatible with the current version of the shell."

Presumably this behaviour comes down not passing an internal version check? Does the extension advertise compatibility with 3.20 to the API?

**Comment by tobimensch** [comment]
https://github.com/zpydr/gnome-shell-extension-taskbar/blob/master/metadata.json

According to the settings in the manifest it should be working with gnome 3.20.

Can you check if this file is identical on your system?

**Comment by xDShot** [comment]
Latest version from git works fine for me on Gnome 3.20.

**Comment by Taijian** [comment]
OK, after editing the metadata.json manually, the extension now loads AND works. So thank you for that pointer!

However, I think it would really help the average user, who is not going to dig through this issue list, if the version on extensions.gnome.org could also be updated - especially as the fix seems to be rather trivial...

**Comment by zpydr** [comment]
Uploaded a new version to extensions.gnome.org with support for gnome 3.20, it is in the review process. Sorry for the delay...
