### ISSUE TITLE
Allow hiding of certain applications

### ISSUE THREAD

**Issue by ashleymcdonald** [zpydr/gnome-shell-extension-taskbar#109]
As per title; a prime example is the ability to hide Conky processes from the list

**Comment by ashleymcdonald** [comment]
conky seems due to initiating via conky-manager; starting normally does not have the same issue. Would still be nice to hide certain apps from the taskbar :)

**Comment by zpydr** [comment]
Added an option to blacklist apps at the bottom of the settings "Tasks (II)" tab.
Just enter the app name in the text field. 
App names can be found at "Show Applications" in the overview. Should the name is cut off choose "Show Details" from the right click menu and copy/paste from there. 
If you intend to blacklist more than one app, separate the app names by comma and space ", "
Example:
Terminal, gedit, Tweak Tool, GNU Image Manipulation Program, Files
