### ISSUE TITLE
Bottom panel only mode improvement

### ISSUE THREAD

**Issue by Arpy222** [zpydr/gnome-shell-extension-taskbar#111]
It would be great, if
1) date menu
2) system menu
(top menu elements) could be added to the bottom panel as well.
In this case, top panel could be turned off without any need.

**Comment by lucazade** [comment]
I agree, it would be nice.. I find the bottom panel extension not so stable to use it alongside the taskbar extension

**Comment by zpydr** [comment]
I will implement this. Thanks

**Comment by zpydr** [comment]
add this extension: https://extensions.gnome.org/extension/949/bottompanel/
