### ISSUE TITLE
multi screen support

### ISSUE THREAD

**Issue by ItamarShDev** [zpydr/gnome-shell-extension-taskbar#117]
Hey 
it would be great if you could add the option to show taskbar on each monitor, with its open applications.
same as workspaces go

**Comment by zpydr** [comment]
yes, will do.

**Comment by willouuu** [comment]
Hello,
What is the status of this function?
thank's

**Comment by lsatenstein** [comment]
Hello William.
I am an end-user of Taskbar (2+years), and I have tested TaskBar with many Gnome versions installed onto many file systems.

As currently presented in the git file, there are no bugs, but gnome-shell has problems with extensions.
With 3.22 and 3.24 versions of Gnome shell, as long as TaskBar was on ext4 or xfs or lvm file system, it functioned flawlessly.  

However, if Gnome 3.22 or Gnome 3.24 was installed on a btrfs file system, it caused the Gnome shell to crash-- the shell would enter a 100% cpu loop, from which the only exit was a kill of the shell task.  This would occur during and after TaskBar was configured

I am testing Taskbar with Gnome 3.25.9, the pending release candidate and with xfs, ext4 lvm and btrfs.   TaskBar does not crash during use. For the most part, Taskbar now does not crash if it,s btrfs.  And that is the same copy of btrfs, identical to what was used for all the testing. The only cause of crashing with btrfs and 3.259, is in the configuration process, i,e installing execution parameters. 

Gnome shell has the problem, and it is a case of           shell blaiming  Taskbar 
If Taskbar works correctly with 3.25.9, and not earlier shell versions,  which of the two is at fault?
If you intend to use TB, it's great, but use it with other than a btrfs file system.

**Comment by willouuu** [comment]
Hello, 
I use Gnome 3.14.2 ( Centos 7 .....) without BTRFS but not understand your answer related with the request to have a taskbar per desktop ^^

**Comment by lsatenstein** [comment]
If Centos was installed using the btrfs file system, you would have problems with TaskBar.  You are using Centos.  If Centos is installed on (default lvm), or xfs or ext4 file system, and you are using GNOME. you should have zero problems with it.

**Comment by willouuu** [comment]
Okay, so how can I activated the taskbar on the primary and secondary monitor?

Thanks

**Comment by Mercotui** [comment]
Has there been any progress on implementing this feature? Is it still planned?
This is currently the only thing holding me back from using this extension.

**Comment by lsatenstein** [comment]
Why do you need TB on two monitors. I use one monitor for documentation and testing, and the other for code writing and the like. TB is on the monitor that is most highly used.

What software would you install that was designed for two monitors?

**Comment by Mercotui** [comment]
While I respect that your workflow might differ from mine, I personally use my second monitor mostly for communications applications, i.e. discord, telegram, some google chrome tabs, email, etc..
So mixing these applications with my text editor, terminal and references is not desired.

**Comment by ErickTucto** [comment]
I like the idea. If I have an application and I want to access some action of this (because I also use [Gnome Global AppMenu](https://github.com/lestcape/Gnome-Global-AppMenu)) I have to make an unnecessary travel to the main monitor. If I had TaskBar on the second screen, that travel would not be necessary

**Comment by lsatenstein** [comment]
Can you investigate centering the taskbar on the bottom? Or use Gnomenu for the first screen and Taskbar for the second, 

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Friday, January 12, 2018, 10:09:06 AM EST, Erick Tucto <notifications@github.com> wrote:  
 
 
I like the idea. If I have an application and I want to access some action of this (because I also use Gnome Global AppMenu) I have to make an unnecessary travel to the main monitor. If I had TaskBar on the second screen, that travel would not be necessary
