### ISSUE TITLE
Not working with GNOME 3.20.3

### ISSUE THREAD

**Issue by cortopy** [zpydr/gnome-shell-extension-taskbar#118]
I just upgraded to Fedora 24 and I'm unable to use the plugin. It's one of my must-haves and any help to set it up again would be much appreciated.

For some of the other plugins it was enough with installing new version, but when  I go to https://extensions.gnome.org/extension/584/taskbar/ I just get a message saying plugin is outdated

**Comment by zpydr** [comment]
You can use the github version instead, see the [TaskBar Installation Wiki](https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Installation#github-repository).
