### ISSUE TITLE
Icon Size ( right n left )

### ISSUE THREAD

**Issue by deepakSP** [zpydr/gnome-shell-extension-taskbar#122]
right now if we change icon size it change all icon sized including right tray .. which i didn't like it I hope you add option to keep right icon size small.
Also if we can have inbuilt option to move top panel to bottom will be cool.
It seems like adding border-bottom has no effect don't know why also it will great if we can style like what i did to active app ( 2px border bottom or top than transparent effect ) kind of windows 10 but its look cool

right now i hacked css n size and it looking awesome i think it has great potential i hope u keep up the good work. 

![screenshot from 2016-08-22 16-11-08](https://cloud.githubusercontent.com/assets/11506967/17852233/c06f32ba-6883-11e6-8e25-3b631f0aabf4.png)

**Comment by zpydr** [comment]
added settings to adjust sizes, will look into the css
