### ISSUE TITLE
Not available for Gnome 3.22

### ISSUE THREAD

**Issue by psiphi75** [zpydr/gnome-shell-extension-taskbar#125]
Unfortunately the Gnome Tweak tool currently does not support Gnome 3.22.  I will be happy to help test that this works with Gnome 3.22.

**Comment by zpydr** [comment]
it's available for version 3.22 here on github. Check the [TaskBar Installation Wiki](https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Installation#github-repository).

**Comment by psiphi75** [comment]
Just tested it, works great.  Thanks for the update.
