### ISSUE TITLE
Unable to install from `extensions.gnome.org` for GNOME Shell 3.22.2

### ISSUE THREAD

**Issue by Marlin-Na** [zpydr/gnome-shell-extension-taskbar#133]
I see the update two days ago which says it has been released to [extensions.gnome.org](https://extensions.gnome.org/extension/584/taskbar/). However, in my case, I am still not able to install from there, using openSUSE tumbleweed with gnome-shell version 3.22.2.  

I would like to report the case, thanks.

**Comment by zpydr** [comment]
It has not yet been reviewed there: [GNOME Shell Extensions Review](https://extensions.gnome.org/review/)
Meanwhile you can install it from the review page following this guide: [TaskBar Installation Wiki](https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Installation#gnome-shell-extensions-website-alternative)
