### ISSUE TITLE
Override the xml schemas 

### ISSUE THREAD

**Issue by Ste74** [zpydr/gnome-shell-extension-taskbar#136]
Hi , i need to disable this key by default after installation in my manjaro pkg : i have set this line
https://github.com/zpydr/gnome-shell-extension-taskbar/blob/master/schemas/org.gnome.shell.extensions.TaskBar.gschema.xml#L118
to false but the apps button on the panel always appear

Thank you

**Comment by zpydr** [comment]
Hi, After changing values in the schema, you have to compile the schema again using the glib-compile-schemas command. You use it on the schemas directory. See: 
https://developer.gnome.org/gio/stable/glib-compile-schemas.html

example:
cd ~/.local/share/gnome-shell/extensions/TaskBar@zpydr/
glib-compile-schemas schemas/
