### ISSUE TITLE
Grouping by app

### ISSUE THREAD

**Issue by jifer** [zpydr/gnome-shell-extension-taskbar#137]
Could someone add grouping by app, so there is only one icon per application?
After hovering on app icon there could be clickable overview of available instances of this app.

Same thing MS Windows users has: http://sites.southseattle.edu/win7/_/rsrc/1472842406692/employees/toggling/w7taskbar.jpg

**Comment by zpydr** [comment]
Hi, this is a very tough one to implement. This has the highest priority on my list, but I got very little time right now.

**Comment by zpydr** [comment]
Added this option.
