### ISSUE TITLE
Need gnome-shell 3.24 compatibility

### ISSUE THREAD

**Issue by dino99** [zpydr/gnome-shell-extension-taskbar#138]
Ubuntu Zesty use gnome-shell 3.23.90 (3.24) version now
but that extension is not yet compatible;

GNOME Shell 3.24 now uses mozjs38 (SpiderMonkey 38) which has stricter syntax rules.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey

 please do asap
Thanks

**Comment by zpydr** [comment]
Hi, Thank you very much for providing this information to me. I will look into this asap.

**Comment by zpydr** [comment]
Done.
