### ISSUE TITLE
Taskbar shadows

### ISSUE THREAD

**Issue by Yazidn** [zpydr/gnome-shell-extension-taskbar#139]
how to remove taskbar shadows? or even reduce the intensity cause it's too dark.
thank you!

**Comment by zpydr** [comment]
Hi, What exactly do you mean? Shadows on the icons? Try with a different icon set, you can customize this via the gnome-tweak-tool.

**Comment by zpydr** [comment]
There are a lot of color and opacity options in the TaskBar settings under the 'Task (III)' tab. For the icons and fonts please check your icon theme in the 'Appearance' tab and the 'Fonts' tab in the GNOME Tweak Tool.
