### ISSUE TITLE
Tasks Alignment Changes on Lock

### ISSUE THREAD

**Issue by maztaim** [zpydr/gnome-shell-extension-taskbar#140]
Tasks alignment changes after locking the screen on Fedora 25 running Gnome 3.22.2 on xorg-x11-server-Xwayland-1.19.1-3 and Taskbar version 53.

Here is what it looks like before locking the screen:
![original-alignment](https://cloud.githubusercontent.com/assets/6034355/23532462/8c3d5c96-ff79-11e6-8569-9045e64a06eb.png)

Here is what it looks like after locking the screen and coming back.
![after-lockunlock-alignment](https://cloud.githubusercontent.com/assets/6034355/23532475/9cadf87e-ff79-11e6-92ee-5a9df48918d2.png)

This stays until I log out, restart the gnome session or set the tasks alignment in the taskbar options.

Let me know if you need any more information.  I'd be happy to provide more details.  If you need a tester, this is very repeatable for me across several systems.

**Comment by zpydr** [comment]
Hi, This has to do with the way gnome loads the elements on the panel. There is a difference when starting up and when unlocking. Gnome does not assign positions to the elements but just adds them to the right side of the previous element. When unlocking the TaskBar is not recognized as such an element. I would have to make a setting to align all elements.

**Comment by zpydr** [comment]
Resolved in 3.24
