### ISSUE TITLE
Taskbar color reset with update to version 55

### ISSUE THREAD

**Issue by doogie544** [zpydr/gnome-shell-extension-taskbar#144]
With the update to version 53 my custom colors are no longer working.  

I can get them to work again by going into the Panels tab and clicking any of the settings OTHER than the color selection.  When you click on any of the arrows the color is instantly back but will reset to default when restarting the computer

Restarting gnome-shell does not fix the color nor does disabling and then restarting "Taskbar" the only way I have been able to get the color working again is as I have described above.

I do have Gradient Top bar installed as well: https://extensions.gnome.org/extension/860/gradient-top-bar/  not sure if that might be causing a conflict but disabling it does not seem to fix the Taskbar color issue.

I am currently running Ubuntu-Gnome 16.10 with nvidia gtx 970 and the most current drivers- 378.13  installed via the Ubuntu package manager, not via the .run available on the nvidia website

**Comment by zpydr** [comment]
Resolved.
