### ISSUE TITLE
Fedora26 Beta 1-4

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#152]
Locks up Gnome user fully, need to killall -u user.   If extension is off, it does not interfere with shell.
Settings can be done if extension is off. Usually works. But who wants to configure taskbar with it disabled? (me)

**Comment by zpydr** [comment]
fixed with latest commit.

**Comment by lsatenstein** [comment]
Thank you, thank you, thank you. 
Your taskbar is the reason I use gnome 3.  Otherwise I would switch to something else.
