### ISSUE TITLE
Request to add a separator between groups [Enhancement]

### ISSUE THREAD

**Issue by Spork-Schivago** [zpydr/gnome-shell-extension-taskbar#155]
Hello,

I love this extension and I love how I can change the spacing between the various groups (ie, the programs I have running and then the Show Desktop button and the Applications button).   I wanted to see if it was possible to add a vertical separator bar between the groups.   I'd like it where we could maybe right click on the bottom task bar and have the option to Add Vertical Separator Bar or something like that, or in the tweak settings extension configuration for Taskbar, we can add as many as we want, and then on the actual bottom taskbar, we just physically move them around.

Thanks!

**Comment by zpydr** [comment]
There are optional separators left and right of the taskbar container and between its components, and there is a separate setting for the spaces between tasks/groups.

**Comment by zpydr** [comment]
They can be set at the 'Separators' tab and with the 'Space between Tasks' option on the 'Tasks (I)' tab in the TaskBar preferences window.

**Comment by Spork-Schivago** [comment]
I've seen and played with the 'Separators' tab and and the "Space between Tasks' options.   But there is no vertical separator bar on my taskbar.   With the 'Separators' tab, when I click various options, it'll increase the spacing between the groups, but no vertical bar appears.   Is this normal?   If so, I was requesting to get that vertical bar.

Also, when I do various things, the Gnome display seems to reset.   Sometimes, all I have to do is open a terminal window.   Usually, the screen just goes blanks and then redraws itself.   Othertimes, it logs me out of X and I have to relog back in.  When I run dmesg, I always see a segfault (after this happens).   It's started since I installed the extension.   It might be a problem with the extension.   Would you like me to send log files to you if it keeps happening?   I run OpenSuSE Tumbleweed x86_64 with Gnome 3.24.2.

I've updated the system the other day and only noticed one crash since, so maybe it's not related to your plugin?

Thanks.
