### ISSUE TITLE
RECOMMENDATION Integrate Notification Alert 

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#158]
Can you integrate the Notification gnome-shell.  That shell allows the task dropdown menu to flash a chosen color, rather than the default white/black

**Comment by Francewhoa** [comment]
@lsatenstein :) There is related setting already existing at TaskBar ---> Settings ---> Tasks (II) tab ---> **Blink**

![Screenshot](https://github.com/zpydr/gnome-shell-extension-taskbar-content/raw/master/screenshot_tasks2.png)

By "Notification gnome-shell" are you referring to this other extension? https://extensions.gnome.org/extension/258/notifications-alert-on-user-menu/

Related tickets #172, #173

**Comment by lsatenstein** [comment]
And what does blink do? Does it blink notifications?  Or does it blink the tasks that are running and noted in the taskbar list?
Does it do the following?
Notifications Alert - GNOME Shell Extensions
  
|  
|   |  
Notifications Alert - GNOME Shell Extensions
   |  |

  |

 
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by Francewhoa** [comment]
@lsatenstein :) I never tried the blink. I just notice that setting.

According to the author it blink tasks when a window demands attention. Source at https://github.com/zpydr/gnome-shell-extension-taskbar/issues/95#issuecomment-216341312

**Comment by zpydr** [comment]
Already implemented. Tasks blink when a window demands attention.

**Comment by lsatenstein** [comment]
Please look at "Notifications Alert"  It generates a blinking altert for any one of the subscribed alerts that are registered, not just the alerts from open tasks within TaskBar
