### ISSUE TITLE
Task application menu not working

### ISSUE THREAD

**Issue by zapat3ro** [zpydr/gnome-shell-extension-taskbar#159]
First off, let me tell you I LOVE this extension; it's by far one of my favs to use on gnome. However, on a pretty fresh Fedora 26 install (installed just on Saturday, Aug. 12. and up-to-day as of today, August 14, 2017) the task application menu (set to right click) is glitchy, and I cannot get it to work.
As you can see on the attached screenshot, the extension is on, and the setting is set to "right click". I tried changing it to middle click to test, but no dice.
I did manage to get the functionality back once, when I turned off all the extensions (using gnome tweak tool) and turning them back on, but that is not working any more.
I am using an Nvidia card with the latest drivers from the negativo17.org repo, and log in to the desktop using the xorg (not wayland) option.
Not sure how to help give more details of what may be causing this, but hopefully this can be looked into in an update or patch.

![task-application-menu_not-working](https://user-images.githubusercontent.com/8976926/29300783-8a519b9c-812c-11e7-8199-ffc790d2fdd0.png)

**Comment by zapat3ro** [comment]
Strangely, the application menu now seems to be working. I've updated my system (Kernel 4.12.5-300) and did not try anything else.

**Comment by zpydr** [comment]
Fixed in next release.
