### ISSUE TITLE
Taskbar won't respect space of Applications/Places left and Date/System right

### ISSUE THREAD

**Issue by br4nnigan** [zpydr/gnome-shell-extension-taskbar#161]
The taskbar will just overlap those native areas when not aligned center.

Due to this I'm really having a hard time aligning things. The desired behavior would be for the taskbar to use all free space, beginning left after the Application/Places and ending right at Date/System menu. Within this space the aligning should take place.

Setting task container width too high will also result in overlapping of those native menus.

**Comment by zpydr** [comment]
Check the 'Tasks Container Width' setting at the 'Tasks (I)' tab. You can set it to eg 6 tasks, then when you open more then 6 windows, the task width will shrink to fit the container. Using labels, you can define the width per task via the 'Tasks Label Width' setting on the same tab.
