### ISSUE TITLE
TaskBar and 3.26

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#162]
The JS lint program produces erroneous results.  TaskBar for my 3 different 3.26 installations (ext4,xfs,lvm) works just fine.  
I have only one issue, and its during the setup and positioning of parameters.
a) I shift the desktop to the left, followed by workspace, followed by favourites, followed by activities followed by tasks.  I typically add 25 extra pixals after activities, and tasks, to delineate the two.

I can on a btrfs file system immediately crash same doing the shifting.

**Comment by lsatenstein** [comment]
I test Taskbar with all pending releases of Gnome, I have tested it with Centos, SUSE, Manjaro and Fedora.  Taskbar can crash if the Linux distribution is installed onto a btrfs file system.  Otherwise, my own experience is as documented.

**Comment by hedgepigdaniel** [comment]
@lsatenstein I also use btrfs and experience crashes of gnome-shell when using taskbar (3.24 in my case, but soon I'll test on 3.26)

What does your stacktrace for gnome-shell look like? Is it anything like these ones? https://bugzilla.gnome.org/show_bug.cgi?id=785657

**Comment by lsatenstein** [comment]
BTRFS and Taskbar

I have installed Gnome 3.26 via Fedora 27.  Taskbar crashes on setup.1) I clicked to enable Favourites. It was OK.  Moving taskbar to bottom panel crashes.However, once all the settings are done. TB runs just fine -- no crashing for what I use.
Taskbar on lvm, ext4 and xfs work just fine.  If extensions are within /usr/... gnome-shell/extensions,  these may crashif /home is moved to an ext4 system, and the extensions are placed therein, --- no crashing.

 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by lsatenstein** [comment]
Configuring Taskbar so locked up my logon directory that it became impossible to get past the password submission.  I would fully lose the keyboard I had some minor success with gnome-xorg. 

What I discovered or I think I discovered is that the schema (compiled) is not being respected.  I set up a 27 pixal width extension to desktop (which I have placed to the right), and it came back as a 600+ value. That means that something is being passed to gnome-shell that allows the gnome-shell to misinterpret the results.  I am not a javascript programmer, but I feel that TB should verify field width sizes.  With btrfs, I enter 27, what I get back is 600+.  
I also must do all setups using gnome-xorg mode, with all settings done on the top bar, before selecting centre bottom.

SUSE linux with btrfs puts /home onto an xfs file system.  When followed that approach, I had very no problems with configuring taskbar. 

Taskbar, once configured, works just fine, as engineered and expected. Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada



       
   
BTRFS and Taskbar

I have installed Gnome 3.26 via Fedora 27.  Taskbar crashes on setup.1) I clicked to enable Favourites. It was OK.  Moving taskbar to bottom panel crashes.However, once all the settings are done. TB runs just fine -- no crashing for what I use.
Taskbar on lvm, ext4 and xfs work just fine.  If extensions are within /usr/... gnome-shell/extensions,  these may crashif /home is moved to an ext4 system, and the extensions are placed therein, --- no crashing.

 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by lexruee** [comment]
@lsatenstein @hedgepigdaniel 
Personally, I don't use this extension, but I can confirm too that gnome-shell 3.24 and a root btrfs filesystem don't play well together with some gnome-shell extensions. Sometimes the gnome-shell crashes multiple times on my Arch system.

**Comment by lsatenstein** [comment]
I am going to test today's patch with btrfs. If it works, then we must ask why the code passed a lint program for JS.
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by Taz8du29** [comment]
have you seen anything in your syslog ? Gnome-shell often verboses alot in here about js problems.

**Comment by zpydr** [comment]
This is beyond anything I can fix within this extension.
