### ISSUE TITLE
Enhancement  Request  Blacklist (do not report running task for selected programs)

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#163]
Is it possible to create a blacklist of certain displayed applications. I run the MacSlow's.Cairo Clock. Gnome atuto starts the program along with autostarting Dropbox.  The clock appears in the tasklist, I would like some way to exclude it and/or long running task.

**Comment by Francewhoa** [comment]
@lsatenstein :) Yes this is possible using "Blacklist Apps". Which is located under “Tasks (III)” ---> “Blacklist Apps”

![Screenshot](https://github.com/zpydr/gnome-shell-extension-taskbar-content/raw/master/screenshot_tasks3.png)

Documentation at https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Settings#taskbar-settings-tasks-iii-tab

Related ticket #109

**Comment by zpydr** [comment]
Already implemented. Should update the docs.
