### ISSUE TITLE
Glitches with "Applications menu" extension

### ISSUE THREAD

**Issue by Pshemas** [zpydr/gnome-shell-extension-taskbar#165]
I'd love to make taskbar working on my Gnome setup (running Gnome on OpenSUSE 42.3), but I'm having some issues when Applications menu extension is installed as well. Sometimes taskbar is displayed before appmenu sometimes after - quite annoying. I'd like to have a clasic appmenu on the very left , then the taskbar - is there a way to set it up?

**Comment by zpydr** [comment]
In the TaskBar settings navigate to the 'Panels' tab. Under 'Align TaskBar' 'Top Panel' click the right arrow ( > ) until the Applications Menu extension shows on the left of TaskBar.

**Comment by zpydr** [comment]
Found a permanent solution. Edit the applications menu extension with admin rights, eg:
`sudo vim /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com/extension.js`
Change '1' to '0' on line 777:
Main.panel.addToStatusArea('apps-menu', appsMenuButton, 0, 'left');
