### ISSUE TITLE
Gnome 3.26 with BTRFS and TaskBar settings are in conflict 

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#167]
Gnome shell 3.24 and 3.261
When TB is installed onto a btrfs system, performing the setup (enabling favourites, shuffling icons to change order of display, adding extra spacing, etc.) causes a user lockup and full keyboard, mouse, and screen loss.
It actually requires a reboot.
Moving $HOME to a ext4 file system, and Taskbar installation is well behaved.
I have tested TB with lvm, ext4, xfs and installation and use are as perfect as can be. That is saying,  TB is just fine. 

With btrfs, if I can get past the setup, here too, TB is just fine.           
Here are some results of my testing.
glib-compile-schema when TB is local matches the previous compiled schema identically.
glib-compile-schema when TB is global (/usr/share/glib2.0/schemas), the existing compiled schema gets bumped up in size by much much more than the size of the locally compiled schema.  Why?
Why with btrfs does $HOME/.config/dconf/user get corrupted, but with lvm, ext4,xfs, it is fine?

My experience is with Fedora 26 and Fedora 27 beta versions of Linux.  There is noting within TB that looks at the host file system.  And yes, I have filed bug reports and gnome-shell crash reports with RedHat.

**Comment by Baltix** [comment]
Please write the URL of Redhat bugreport

**Comment by lsatenstein** [comment]
The problems have been identified as being about btrfs. 
    
   - To
      -        
      -   lsatenstein@yahoo.com  
 
      -     

  
Message body
 https://bugzilla.redhat.com/show_bug.cgi?id=1464294

 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada
