### ISSUE TITLE
Help with Dash to Panel?

### ISSUE THREAD

**Issue by Bindea** [zpydr/gnome-shell-extension-taskbar#168]
@zpydr

https://github.com/jderose9/dash-to-panel/issues/208

I know this is a big ask and i hope you don't find it rude but is there any chance you could post a snip of your code in the above thread that is used to Ungroup Applications so they are shown separately on the taskbar?

Thanks

**Comment by zpydr** [comment]
TaskBar hides the duplicate tasks when the 'group' setting is enabled.
