### ISSUE TITLE
Just one distorted icon

### ISSUE THREAD

**Issue by puhach** [zpydr/gnome-shell-extension-taskbar#171]
Hello.

For first, thank you for nice extension :)

It's strange but just one app has with distorted icon on start. It's Spotify.
http://dl3.joxi.net/drive/2017/12/01/0025/2828/1698572/72/69e4322a56.jpg

After switch to another app the icon rebuild to normal view.
http://dl4.joxi.net/drive/2017/12/01/0025/2828/1698572/72/3566befa98.jpg

May you comment it?

Thanks in advance.

**Comment by puhach** [comment]
P.S. I use latest Manjaro-Gnome.

**Comment by lsatenstein** [comment]
I am an end-user, not the owner/developer

**Comment by zpydr** [comment]
Try editing the Spotify desktop entry:
https://wiki.archlinux.org/index.php/Desktop_Entries
Alternatively install the gui "alacarte" package ("Main Menu") and tweak the icon there.
