### ISSUE TITLE
[Wayland Bug] Extension doesn't show last opened application icon properly like nautilus, gnome tweaks

### ISSUE THREAD

**Issue by ceyhunnabiyev** [zpydr/gnome-shell-extension-taskbar#175]
You see on the  following  picture, nautilus icon is another icon on Wayland. It doesn't matter which icon-theme is selected from Gnome Tweaks, but on Xorg It is OK:
![screenshot from 2018-01-06 15-24-39](https://user-images.githubusercontent.com/5506156/34639345-cf9dfa5a-f2f7-11e7-8f5e-b183b69e381e.png)

**Comment by zpydr** [comment]
fixed with last commits.

**Comment by ceyhunnabiyev** [comment]
@zpydr , Severe bug appeared on Wayland. **Opening non-mutter applications (google-chrome, visual studio code and etc..) causes gnome-shell crash.** After disabling this extension everything works fine.

**Comment by ceyhunnabiyev** [comment]
Gnome-crash log:
```
Stack trace of thread 6211:
#0  0x00007fca61aa3c70 raise (libpthread.so.0)
#1  0x000055fa36101562 n/a (gnome-shell)
#2  0x00007fca61aa3dd0 __restore_rt (libpthread.so.0)
#3  0x00007fca6170f860 raise (libc.so.6)
#4  0x00007fca61710ec9 abort (libc.so.6)
#5  0x00007fca609eb3e6 g_assertion_message (libglib-2.0.so.0)
#6  0x00007fca609eb47c g_assertion_message_expr (libglib-2.0.so.0)
#7  0x00007fca5f631c0a n/a (libmutter-clutter-1.so)
#8  0x00007fca5f634c79 n/a (libmutter-clutter-1.so)
#9  0x00007fca5f640f0a n/a (libmutter-clutter-1.so)
#10 0x00007fca60c9dc5d g_closure_invoke (libgobject-2.0.so.0)
#11 0x00007fca60cb1c28 n/a (libgobject-2.0.so.0)
#12 0x00007fca60cba806 g_signal_emit_valist (libgobject-2.0.so.0)
#13 0x00007fca60cbb240 g_signal_emit (libgobject-2.0.so.0)
#14 0x00007fca5f64273e clutter_actor_show (libmutter-clutter-1.so)
#15 0x00007fca5f645111 clutter_actor_add_child (libmutter-clutter-1.so)
#16 0x00007fca5ea1015e st_bin_set_child (libst-1.0.so)
#17 0x00007fca60ca5c77 g_object_setv (libgobject-2.0.so.0)
#18 0x00007fca60ca6c7f g_object_set_property (libgobject-2.0.so.0)
#19 0x00007fca5f97f763 n/a (libgjs.so.0)
#20 0x00007fca58322eff n/a (libmozjs-52.so.0)
#21 0x00007fca58323447 n/a (libmozjs-52.so.0)
#22 0x00007fca58324aea n/a (libmozjs-52.so.0)
#23 0x00007fca5833743f n/a (libmozjs-52.so.0)
#24 0x00007fca57eb319a n/a (libmozjs-52.so.0)
#25 0x00007fca5833dd0b n/a (libmozjs-52.so.0)
#26 0x00007fca5833570e n/a (libmozjs-52.so.0)
#27 0x00007fca58336464 n/a (libmozjs-52.so.0)
#28 0x00007fca58336918 n/a (libmozjs-52.so.0)
#29 0x00007fca580355e3 n/a (libmozjs-52.so.0)
#30 0x00001428a57bcab6 n/a (n/a)
```

**Comment by zpydr** [comment]
thanks for the feedback. tested the latest commits on a fedora 27 gnome wayland vm, there I installed google-chrome as per https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/ and did not experience any issues. what os are you trying this on?

**Comment by ceyhunnabiyev** [comment]
@zpydr ,
Manjaro Gnome Stable Branch,
Gnome-shell - 3.26.2+14+g64c857e3f,
gjs - 1:1.50.4-1,
Google Chrome - 65.0.3325.181-1 version

**Comment by zpydr** [comment]
I'll test with manjaro, thanks

**Comment by zpydr** [comment]
installed Manjaro GNOME Edition (17.1.7) x64 from https://manjaro.org/get-manjaro/
removed the existing version of TaskBar with `sudo rm -r /usr/share/gnome-shell/extensions/TaskBar@zpydr/`
installed the latest commits from github with `sudo git clone https://github.com/zpydr/gnome-shell-extension-taskbar.git /usr/share/gnome-shell/extensions/TaskBar@zpydr/`
disabled all extensions via gnome-tweak-tool and enabled taskbar.
found that it works fine by itself but seems to conflict with other extensions, could not really make out which one.
can you confirm? what other extensions are you using? thanks

**Comment by zpydr** [comment]
it seems to be the user themes. can you please disable this extension for testing?

**Comment by zpydr** [comment]
more specifically it is not the user themes extension itself, but the pre-configured Adapta user themes. when changing it to default in tweak tool, it does not crash.

**Comment by zpydr** [comment]
yeah , 'default' does not work great either, it lags, might be an issue with the user themes extension after all...

**Comment by zpydr** [comment]
enabled all the other available extensions here as well (disabled user themes) and its working fine, so I think this is related to the theme settings available in the taskbar extension. let me know your opinion.

**Comment by ceyhunnabiyev** [comment]
Yes, strange. After disabling user themes, it has worked.

**Comment by ceyhunnabiyev** [comment]
@zpydr , I also tried with arc-theme. No success. However I notice  strange behavours.
1. Just I opened the Gnome-Tweaks(don't close). Then I opened Google-chrome, Gnome-shell doesn't crash.
2. Only I opened Google-Chrome(without Gnome Tweaks), then gnome-shell crashes.

I tested these behavours more times.

**Comment by zpydr** [comment]
this is all working fine here on xorg and wayland, using the 'default' user theme. can you please export and reset all your taskbar settings? also please disable all other extensions.

**Comment by lsatenstein** [comment]
Have you created a bug report?
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by zpydr** [comment]
@ceyhunnabiyev yes, with Manjaro GNOME Edition (17.1.7) x64 on xorg and wayland.

**Comment by ceyhunnabiyev** [comment]
If you don't have problem, just ignore it. If I notice something severe, I will share with you. 
Thank you for taking time for me.
