### ISSUE TITLE
How to remove task icons above bottom panel?

### ISSUE THREAD

**Issue by markd89** [zpydr/gnome-shell-extension-taskbar#177]
I'm using the extension (and it is friggin awesome!).  I am running Debian Stretch/Gnome 3.22.

The picture below is the bottom left of my screen. You see the bottom panel with the Show Desktop button and a terminal window icon. Normal.

Above that is a sliding panel which shows one of my running applications. I can click the < and it will shrink. How can I remove it permanently?
![gnome322](https://user-images.githubusercontent.com/690446/36457641-f28c0c74-165f-11e8-9ca0-d97b4fdf1eae.png)

Thanks!
Mark

**Comment by Taz8du29** [comment]
This is not the goal of this extension. You may have a look at an extension like [TopIcon+](https://github.com/phocean/TopIcons-plus/) for this purpose

Warning : because of the way gnome implements some extension functionnalities, making some bugs un-patchable, Phocean dropped support for TI+.

**Comment by markd89** [comment]
Thanks very much for the info! :-)

**Comment by Taz8du29** [comment]
You're welcome !
