### ISSUE TITLE
Hide one open task on bottom taskbar?

### ISSUE THREAD

**Issue by markd89** [zpydr/gnome-shell-extension-taskbar#178]
Hi,

I have the running tasks in the bottom panel. I use Pidgin and when I open a chat window, I then have both the main Pidgin window (buddy list) as well as the chat window.

Is it possible to have the bottom panel exclude the main Pidgin window?

thanks!
Mark

**Comment by zpydr** [comment]
You can exclude the app via the 'Blacklist Apps' setting on the Tasks (III) tab, but this will probably exclude all windows of this app.
