### ISSUE TITLE
Add menu to ignore some apps

### ISSUE THREAD

**Issue by vallerydelexy** [zpydr/gnome-shell-extension-taskbar#182]
![screenshot from 2018-03-01 13-42-14](https://user-images.githubusercontent.com/17786532/36830747-8b42a790-1d57-11e8-9d11-09182dcf5773.png)

i am running ubuntu 17.10
the java-lang-thread is a module from Xtreme Download Manager

and i dont want that module show up in the top bar

can you please add a menu to ignore some apps please

**Comment by zpydr** [comment]
Open the app in question. Then open the 'Preview' tab in the TaskBar settings window and set the 'Tasks Label Preview' to 'App Name'. Hover the app-icon on the top bar with the mouse and note the name that appears. Then switch to the 'Tasks (III)' tab and enter the name into the 'Blacklist Apps' field. Turn the setting on.
