### ISSUE TITLE
Add support for gnome-shell 3.28

### ISSUE THREAD

**Issue by soupault** [zpydr/gnome-shell-extension-taskbar#183]
GNOME 3.28 has been recently released (https://www.gnome.org/news/2018/03/gnome-3-28-released/), and is already available in the Archlinux repositories.
Please, consider adding the support for this version.

P.S. Thank you very much for the extension!

**Comment by lsatenstein** [comment]
There was nothing to do, it works for me with Gnome 3.28 on two distributions   FEDORA 28 Compose, and SUSE Tumbleweed,
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by soupault** [comment]
I confirm. Works fine for me so far on the latest Archlinux.

**Comment by zpydr** [comment]
Is supported.
