### ISSUE TITLE
Ubuntu 18.04: "TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined"

### ISSUE THREAD

**Issue by pejobo** [zpydr/gnome-shell-extension-taskbar#191]
The extension stopped working with Ubuntu 18.04, journalctl says:

gnome-shell[4931]: Extension "TaskBar@zpydr" had error: TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined

$ gnome-shell --version
GNOME Shell 3.28.1

**Comment by pejobo** [comment]
I see that the version at https://extensions.gnome.org/extension/584/taskbar/ is v56, code here is v57 and this bug seems to be already fixed. 
Workaround for me is enabling the "hot corner setting" in the config, section "misc".

**Comment by Taz8du29** [comment]
Have a look at #180
@zpydr removed the functionnality because it's now included in gnome-tweak-tool.
