### ISSUE TITLE
Missing disable hot corner feature

### ISSUE THREAD

**Issue by hashstat** [zpydr/gnome-shell-extension-taskbar#195]
I noticed recently that the top-left hot corner was working again (no longer disabled) and went on the hunt to determine why. I was pretty sure I was using the TaskBar extension to disable that annoying feature, but I couldn't find the setting anywhere in the configuration panels. After digging around on GitHub, I finally found commit a805d69, which purports to be a "hot corner fix," that appears to disable the option for gnome-shell 3.26 and above. I'm using 3.28.

That leaves me wondering: what was the reason for the "fix"?

Thanks

P.S. - This is probably my favorite extension. The Gnome experience would suffer without it.

**Comment by Taz8du29** [comment]
Hello,

Since Gnome-shell v3.26, the option for disabling hot corners can be found in the gnome-tweak-tool utility:
![image](https://user-images.githubusercontent.com/13140104/45252675-d6626000-b35a-11e8-9adf-bc6fc8c5c27b.png)
