### ISSUE TITLE
Ubuntu 18.10 Cosmic Cuttlefish Error

### ISSUE THREAD

**Issue by TeknoMobil** [zpydr/gnome-shell-extension-taskbar#208]
Hi Doesn't work on my Ubuntu 18.10 Cosmic Cuttlefish. Error is shown on my list of extensions

**Comment by grizzlysmit** [comment]
yeah mine too gnome-shell version is GNOME Shell 3.30.1

**Comment by Popyllol** [comment]
Yep, it is broken in GNOME Shell 3.30.1 :-(.
This is reallay sad!

**Comment by lsatenstein** [comment]
The question to ask and answer is "What is broken? " I inherited a patched version that works for me. Message me next week for a tarfile of the version I use.  (I am on vacation)

Sent from Yahoo Mail on Android 
 
  On Thu, 15 Nov 2018 at 11:19 PM, Lars<notifications@github.com> wrote:   
Yep, it is broken in GNOME Shell 3.30.1 :-(.
This is reallay sad!

**Comment by Popyllol** [comment]
> The question to ask and answer is "What is broken? " I inherited a patched version that works for me. Message me next week for a tarfile of the version I use.  (I am on vacation) Sent from Yahoo Mail on 

Exactly this is the question and I don't know where to look for Gnome shell extension problems.
I would like to test the tar file!
Have a nice vacation and thank you for the answer!
   Lars

**Comment by CoryAlbrecht** [comment]
Automatically detected errors:

  TypeError: global.screen is undefined

================

Version information:

    Shell version: 3.30.1
    Extension version: 57

Another Gnome xtentions that I use which has fixed the problem: https://github.com/micheleg/dash-to-dock/pull/770#issue-199936075
