### ISSUE TITLE
Please restore the source in case somebody wants to fork and try to continue

### ISSUE THREAD

**Issue by CoryAlbrecht** [zpydr/gnome-shell-extension-taskbar#209]
Like the title says. This is the strength of the OSS community, and maybe there's somebody out there with the skills and time to continue the most wonderful plugin for Gnome.

**Comment by lsatenstein** [comment]
If you visit github, therein you will find the git repository for the source.

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Thursday, November 22, 2018, 6:32:27 p.m. EST, Cory Albrecht <notifications@github.com> wrote:  
 
 
Like the title says. This is the strength of the OSS community, and maybe there's somebody out there with the skills and time to continue the most wonderful plugin for Gnome.

**Comment by lsatenstein** [comment]
I have a recent version from Github

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada
lsatenstein@yahoo.com
 

    On Thursday, November 22, 2018, 6:32:27 p.m. EST, Cory Albrecht <notifications@github.com> wrote:  
 
 
Like the title says. This is the strength of the OSS community, and maybe there's somebody out there with the skills and time to continue the most wonderful plugin for Gnome.

**Comment by zpydr** [comment]
The latest updates can be found at 
https://github.com/zpydr/gnome-shell-extension-taskbar/tree/39b36aba2611c42cefbbf9beab60d46ce75ec82c
