### ISSUE TITLE
Applied changes to extension.js and meta.json  -- not working with Fedora 30 or 31beta

### ISSUE THREAD

**Issue by lsatenstein** [zpydr/gnome-shell-extension-taskbar#216]
I applied changes to extension.js and meta.json  -- TaskBar is not working with Fedora 30 or 31beta

Can someone make available on Dropbox or Google Drive or other public location of their working version of TaskBar.  

In the interrim, I am using frippery Panel Favorites as my TaskBar alternative.  
Can we not rename/ fork TaskBar to TaskBar2  and get help to maintain it for the more resent gnome versions.

**Comment by c0ldplasma** [comment]
Fixed version for Fedora 31 Gnome 3.34: #217

**Comment by c0ldplasma** [comment]
Created a fork for supporting new gnome versions: https://github.com/c0ldplasma/gnome-shell-extension-taskbar/

**Comment by lsatenstein** [comment]
Just tried your Fork, it does not work.  I wish I knew what the include files did within extension.js
I have a tarfile that is more recent than the one you forked.  It runs but some over extensions cause a disable/enable, TB fails to re-enable.  If you want to receive a  tarfile of my version of TB, use my name followed by at yahoo dot com.  Put TaskBar in the title,

**Comment by lsatenstein** [comment]
replace (line 2) over -->other
