### ISSUE TITLE
Taskbar alignment lost upon sleep mode

### ISSUE THREAD

**Issue by AlexisWeinreb** [zpydr/gnome-shell-extension-taskbar#32]
Hi,

Normally, I have aligned the icons in order to have:
Applications; Tasks; Name of the current task.

![capture d cran de 2014-01-11 23 08 52](https://f.cloud.github.com/assets/6378955/1895026/99fb6bd8-7b0c-11e3-9e48-405dcdf94c8c.png)

Whenever my computer comes out of sleep mode (laptop lid closed), the order is changed and becomes:
Applications; Name of current task; Tasks

![capture d cran de 2014-01-11 23 14 37](https://f.cloud.github.com/assets/6378955/1895036/6483a938-7b0d-11e3-9cf2-c48b3d6ceb32.png)

On TaskBar v35, it was solved simply by opening TaskBar's preferences (right-click on the Desktop Button), on v38, it's solved by clicking the "align TaskBar" buttons in the preferences.

So, I think it is a bug? I have GNOME Shell 3.10.2.1

**Comment by zpydr** [comment]
Solved.
