### ISSUE TITLE
Hide active window

### ISSUE THREAD

**Issue by justcomplaining** [zpydr/gnome-shell-extension-taskbar#58]
Add an option to hide the active window as it's shown exactly next to it... :)

**Comment by justcomplaining** [comment]
It shows the standard one, so another in the taskbar is not necessary.

**Comment by zpydr** [comment]
Do you mean the app menu?

**Comment by zpydr** [comment]
or the actual window ?

**Comment by zpydr** [comment]
Added application menus.

**Comment by dftst0** [comment]
I believe the original request was to hide the active task from the taskbar so that the active task menu can be accessed from the built-in application menu, and not just be able to hide the application menu.
