### ISSUE TITLE
Separate options for showing window titles and application names.

### ISSUE THREAD

**Issue by justcomplaining** [zpydr/gnome-shell-extension-taskbar#59]
Seperate options for showing window titles (or file names/whatever it may be) and application names. Maybe even filtering (so that if no title other than the application name is available, it's shown, if there is, it's not...). Now I have for example

Prefences for XY
Preferences for XY

and

Firefox Web Browser
Issue XY github.com - Mozilla Firefox

That's awfully redundant ;)

**Comment by zpydr** [comment]
Added additional preview options with the last push.
