### ISSUE TITLE
defautl app menu is displayed to left of tasks

### ISSUE THREAD

**Issue by anirudhnihalani** [zpydr/gnome-shell-extension-taskbar#66]
Hi,

First of all Thank you very much for this Great extension!!! I had your extension installed on several machines. On most of them default app menu is showing up on rightside of tasks however on some the default app menu is showing up on the leftside of tasks as shown in the attached picture. Now whenever I switch applications, based on the length of application title the default app menu either expands or contracts which causes tasks to move right or left accordingly from their current position. I would like to have the tasks fixed which would be the case when default app menu is displayed to the right of tasks. So all I want is to move that default app menu to the right of tasks. Please let me know how to fix this.
![taskbar](https://cloud.githubusercontent.com/assets/7869622/5989676/3adcf0a8-a9b5-11e4-92ac-9d1bc0a4f7bb.png)

**Comment by zpydr** [comment]
In the Preferences under Panels choose Align TaskBar and move it all the way to the left. The App Menu should now appear on the right side of TaskBar.
