### ISSUE TITLE
Scroll wheel to cycle through windows in blank space

### ISSUE THREAD

**Issue by rgeary1** [zpydr/gnome-shell-extension-taskbar#68]
Whilst implementing #67, I noticed that using the scroll wheel in the bottom panel didn't work in the blank area to the right of the tasks. Again, using Chrome as my reference for behaviour, this was unexpected.  Also the right-click menu on the blank area gave me the menu options of "Change Background" and "Settings", but this was actually the menu for the Gnome background beneath the bottom panel - I expect this isn't by design.

I've implemented a fix : https://github.com/rgeary1/gnome-shell-extension-taskbar/commit/ae4d8a55285cd348edc62d9096cf30d3c425340d

The fix took a bit longer than I expected to implement, partly because I'm new to gnome development, but mostly because scroll-event event is only picked up by St.Button, not St.BoxLayout, so I had to add empty Buttons to fill the blank space.

It's not yet a pull request as I've only tested it on 3.14.  How would I test it sufficiently to get it merged?

Thanks!

**Comment by zpydr** [comment]
Thank you. It is now possible to scroll on the Tasks Conatiner.
