### ISSUE TITLE
Add window title next to window icon

### ISSUE THREAD

**Issue by thelan** [zpydr/gnome-shell-extension-taskbar#7]
Hello,

I think it would be perfect if we can add the window title next to the icon in the task list.

**Comment by Robert42** [comment]
I also agree, that adding an (optional) label has some value. Following [Fitts Law](http://en.wikipedia.org/wiki/Fitts%27s_law), the faster the target you want to click, the faster you can navigate. So additional width (by a text) will allow the users to navigate quicker :)

**Comment by skochxxl** [comment]
Hi, I really love this extension and also wanted to have the window title available so I simply changed the file "extension.js". In function "addTaskInList" I replaced this line (nearly at the top):

            let buttonTask = new St.Button({ style_class: "tkb-task-button", child: app.create_icon_texture(this.iconSize) });

by these lines:

            let appBox = new St.BoxLayout({ style_class: 'tkb-task-box' });
            appBox.add( app.create_icon_texture(this.iconSize) );
            appBox.add( new St.Label({ text: app.get_name(), style_class: 'tkb-task-box-label' }) );
            let buttonTask = new St.Button({ style_class: "tkb-task-button", child: appBox });
It's not the best way to do it because it it lost after next update and it's not configurable but it's a fast workaround and maybe something like this will be integrated in a later version.

**Comment by skochxxl** [comment]
I forgot to mention that I also added something at the end of "stylesheet.css"

.tkb-task-button
{
    padding-left: 1px;
    padding-right: 1px;
}
.tkb-task-button:active-task-frame
{
    border-color: rgba(0,0,0,0);
    background-image: none;
}

.tkb-task-button:active-task-frame .tkb-task-box
{
    border-color: #9A7200;
}

.tkb-task-box 
{
    border: 1px solid gray;
    border-radius: 5px;
    color: #bbb;
    padding: 0;
}

.tkb-task-box-label 
{
    width: 50px;
    overflow: hidden;
    padding: 2px 0;
margin-bottom:1px;
}

**Comment by lucazade** [comment]
any chance to have label next to window icon?

**Comment by zpydr** [comment]
Just added that, you can download it here: [Latest zip file](https://github.com/zpydr/gnome-shell-extension-taskbar/archive/master.zip) and check the [Installation Wiki](https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Installation#github-repository).
