### ISSUE TITLE
Enabling TaskBar brings the shell to a crawl; disabling TaskBar solves the issue

### ISSUE THREAD

**Issue by alptekinsanli** [zpydr/gnome-shell-extension-taskbar#77]
I find this to be the most useful extension in the entire collection; however, whenever I enable it, the shell slows down to a crawl -- all menus, popups, etc., in *all* GTK applications hang for several seconds on end. I don't understand why or how, but seeing as disabling TaskBar solves the issue, and enabling it brings it back, I'm forced to infer that the extension is the cause.

I've had the exact same behavior in openSUSE Tumbleweed running GNOME 3.14 and 3.16; as well as Fedora 21 running GNOME 3.14. Not sure if relevant, but I've been on proprietary nvidia drivers the whole time (the 346 and the 349 series).

**Comment by skochxxl** [comment]
I'm having the same issue. And the shell slows down over time more and more.

**Comment by damianavila** [comment]
Same here...

**Comment by Gwend4l** [comment]
Same issue here, it gets worse and worse over time. And it's definitely better when disabling the extension. Maybe a memory leak?

**Comment by Obihoernchen** [comment]
Same here.
Really looks like a memory leak :(

**Comment by Krishath** [comment]
+1

**Comment by zpydr** [comment]
Please reset TaskBar completely (About tab : Reset all) including the top/bottom panel- and icon- "background color" and let me know if the issue persists. Thank you.

**Comment by Obihoernchen** [comment]
Did "Reset all". Afterwards ALT + F2 "r".
After some time there is the same problem. Shell becomes very laggy.
Especially the overview.

Fedora 22 with Gnome 3.16.

**Comment by zpydr** [comment]
Thank you for confirming this, it will help to narrow down where the issue really is.

**Comment by zpydr** [comment]
This issue should be resolved with commit f3d87a62d0b926d012d81120d3b04dce6c742002 .

**Comment by Obihoernchen** [comment]
Mhh looks a lot better now but after a few hours it get's really laggy again (opening app overview for example).
