### ISSUE TITLE
Bottom panel hides the bottom of windows on dual monitor setup

### ISSUE THREAD

**Issue by ferares** [zpydr/gnome-shell-extension-taskbar#78]
When the primary screen is set on top of the second monitor the bottom panel covers the bottom of the windows (like the status bar on Gedit or Libre Office).

ok:
![ok](https://cloud.githubusercontent.com/assets/12473537/7666477/1861e128-fbbd-11e4-8627-c485764430bd.jpeg)

issue:
![issue](https://cloud.githubusercontent.com/assets/12473537/7666479/1a28f8a2-fbbd-11e4-9bf5-811987fb7010.jpeg)

**Comment by zpydr** [comment]
This does not look like the TaskBar bottom panel... Anyways I will look into this

**Comment by zpydr** [comment]
Cannot reproduce this issue. Looks like this extension: https://extensions.gnome.org/extension/602/window-list/
