### ISSUE TITLE
Dual screen: slow menu, slow tooltip and slow window move to other screen

### ISSUE THREAD

**Issue by nathan818fr** [zpydr/gnome-shell-extension-taskbar#81]
This is in part the same problem there: https://github.com/zpydr/gnome-shell-extension-taskbar/issues/64

When you are in dual screen after some time (no latency at start, then more and more progressively), some elements cause significant lags and cpu peak on gnome-shell process:
- When we pass a window from one screen to another
- When a floating element closes / disappears (a tooltip, an autocomplete window, a menu - those that are displayed after the right clicks)

The bug happens much faster when you use an IDE that displays a lot of autocompletion window (when I code it's horrible! ^^).
___
###### My configuration
OS: Debian Jessie (Kernel 3.16.0-4-amd64)
Memory: 15.6 GiB
Processor: Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8
Graphics: Intel® Haswell Mobile (i also have an NVidia GTX 970M but I use it only for specific applications with bumblebee / 'optirun')

Gnome Version 3.16.2
___
###### More informations
When that bug append gnome-shell can up to 100% CPU and freeze for 5/10 seconds.

Commits bab8e3406bba6fcf266910ff55958efaaa1f1d97 and after are affected.
Commits ef262a3554f5705295195dd72543f459088d2f82 and before aren't affected.

So that bug was certainly caused by https://github.com/zpydr/gnome-shell-extension-taskbar/commit/a9230548587ea990cfc3dd4925251c7cb1d9a45d (i don't think it comes from https://github.com/zpydr/gnome-shell-extension-taskbar/commit/8cedbf9ddbfb3e3a7aa19618d24585d59c375dd8)

I will test the latest version with this commit reverted...

**Comment by zpydr** [comment]
Thank you for the very detailed info and especially for looking into the commits. Unfortunately I have a hard time to reproduce this bug myself using multiple screens....

**Comment by nathan818fr** [comment]
The bug seems not to occur for some time now (probably after upgrade / dist-upgrade).

**Comment by zpydr** [comment]
Thanks for the fast reply, I'll close this.

**Comment by RKBK** [comment]
This problem still occurs to me, with the most recent version of gnome-shell-extension-taskbar, in ubuntu 15.10.

**Comment by ltsampros** [comment]
I'm still having this with 55 and gnome-shell 3.18 on Ubuntu 16.04. I'm using the nvidia driver if that matters.
