### ISSUE TITLE
The task bar does not stay where I put it.

### ISSUE THREAD

**Issue by noah2828** [zpydr/gnome-shell-extension-taskbar#83]
I like your extension but it has a habit of moving towards the left when in use. alt+f2 r fixes it but it always happens again. 
![screenshot from 2015-08-10 19 38 29](https://cloud.githubusercontent.com/assets/13205749/9186812/71e44132-3f97-11e5-8d44-7095604bef12.png)
 how it should look after I adjusted the panel location or r command.
![screenshot from 2015-08-10 19 40 16](https://cloud.githubusercontent.com/assets/13205749/9186829/a9ea1412-3f97-11e5-873a-241b84764a19.png)

**Comment by ExtraordinaryBen** [comment]
Did you install it using extensions.gnome.org? I think an older version of TaskBar is hosted there. If you install from the master branch here on GitHub the problem should go away. It has for me anyway. (Looks like it was [resolved as of Feb 21, 2015](https://github.com/zpydr/gnome-shell-extension-taskbar/issues/32))

**Comment by noah2828** [comment]
ok thanks
