### ISSUE TITLE
Windows become unresponsive

### ISSUE THREAD

**Issue by Krishath** [zpydr/gnome-shell-extension-taskbar#84]
Running under: Gnome 3.16

Using this extension makes **every** window unresponsive after a while. I use Guake a lot and the fullscreen toggle animation is very very laggy.

**Comment by Obihoernchen** [comment]
Same as https://github.com/zpydr/gnome-shell-extension-taskbar/issues/77 I think.

**Comment by Krishath** [comment]
Yes. Closing this one in favour of #77
