### ISSUE TITLE
Gnome 3.18 compatibility

### ISSUE THREAD

**Issue by vladimiry** [zpydr/gnome-shell-extension-taskbar#86]
No description.

**Comment by ExtraordinaryBen** [comment]
[Waiting for my pull request to be accepted,](https://github.com/zpydr/gnome-shell-extension-taskbar/pull/85) until then you can [give my fork a try.](https://github.com/ExtraordinaryBen/gnome-shell-extension-taskbar) 

I haven't tested every feature, but so far it's been working fine for me. Let me know if you have any issues.

**Comment by vladimiry** [comment]
Works fine so far on Gnome 3.18, thanks.
