### ISSUE TITLE
Minimize animation should target icon in TaskBar

### ISSUE THREAD

**Issue by jhasse** [zpydr/gnome-shell-extension-taskbar#89]
Right now the the minimize animation of a window goes to the top left corner. 

I'm using this extension: https://extensions.gnome.org/extension/949/bottompanel/

so this looks a little bit off. Would be great if the animation targets the window icon in the taskbar.

**Comment by zpydr** [comment]
Added icon_geometry with the last commit, this will target the related task box when minimizing and un-minimize from the same.
