### ISSUE TITLE
Group windows of the same application - do not show separate icons for each window

### ISSUE THREAD

**Issue by Baltix** [zpydr/gnome-shell-extension-taskbar#9]
Currently taskbar extension displays separate icon for each window, even if windows are from the same application, for exampe when I open 5 PDF documents, I get 5 icons in taskbar.
Please group windows of the same application - show only one icon in taskbar (don't show separate icons for each window) and display thumbnails of all windows when mouse cursor is over application icon in the taskbar.
This feature is already implemented in other similar gnome-shell-extensions, see:
http://packages.linuxdeepin.com/deepin/pool/main/d/deepin-gse/deepin-gse-dock_1.1.8_all.deb (you can also download source tar.gz from http://packages.linuxdeepin.com/deepin/pool/main/d/deepin-gse/ or https://extensions.gnome.org/extension/265/deepin-enhanced-dock/)
and https://extensions.gnome.org/review/1617

**Comment by soncodi** [comment]
:+1:

**Comment by tomasvanrijsse** [comment]
:+1:

**Comment by sebalis** [comment]
I would love to see this implemented, but please provide options to enable or disable this behaviour. In particular choose whether to just group icons for the same application together or also collapse these into a single icon. Also if reordering of icons as requested in #9 is implemented and icons are not collapsed, I would very much like to be able to reorder icons within an application group as well. If this is confusing to others it could be made available by pressing a modifier key to drag icons within an application group.

**Comment by HunterGraubard** [comment]
I'd like to chime in to say that I would love this feature. It's one of the hallmark features of a good task bar in my opinion (Plasma, Unity, Windows, etc. all offer it), and it's useful both in terms of quickly finding the right window and saving space for other applications. Is this difficult to implement?

**Comment by Maxence** [comment]
I agree, I would love to get an option to group by application like the window list extension for gnome.

Great work btw, good luck!

**Comment by zpydr** [comment]
Added an option to group app windows in the settings under the 'Task (I)' tab 'Sort or Group Tasks by Application'. Choose 'Group' or 'Group Workspace'. If there is more than 1 window per app, they will be grouped. When grouped the windows will be added to the top of the application menu. Also the preview will append '(Group)' to the app name.

**Comment by rogerweb** [comment]
@HunterGraubard, did you manage to find a GNOME taskbar that supports re-ordering the buttons associated with the active windows? For me this is the only feature that taskbar is missing.
