### ISSUE TITLE
instability due to undefined hotCorners code?

### ISSUE THREAD

**Issue by rik-shaw** [zpydr/gnome-shell-extension-taskbar#90]
I have been trying to figure out why taskbar is so unstable when restarting gnome-shell.  It seems definitely related to hotcorner settings, and then I have found that when restarting in a terminal I am getting the following output (I am running gnome-shell 3.16 with Ubuntu 15.10 'wily'):

(gnome-shell:3158): Gjs-WARNING **: JS ERROR: TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined
TaskBar.prototype.disable@/usr/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:396
TaskBar.prototype.onParamChanged@/usr/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:265
loadTheme@resource:///org/gnome/shell/ui/main.js:312
ThemeManager<._changeTheme@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:65
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
ThemeManager<.enable@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:24
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:128
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:170
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
_emit@resource:///org/gnome/gjs/modules/signals.js:124
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
init@resource:///org/gnome/shell/ui/extensionSystem.js:346
_initializeUI@resource:///org/gnome/shell/ui/main.js:209
start@resource:///org/gnome/shell/ui/main.js:120
@<main>:1

**Comment by rik-shaw** [comment]
Update: this error and a general crashing of Taskbar comes as a result of multiple extensions trying to disable hotcorners.  For example, I also am using gnomenu.  When gnomenu is set to disable the activities hotcorner, then when loading Taskbar the error comes.  If I keep gnomenu to NOT disable the activities hotcorner, then Taskbar will load without error.

**Comment by zpydr** [comment]
Should be resolved now when the hot corner is not deactivated.
