### ISSUE TITLE
Show hover items (window name, preview) above bar when using "Bottom Panel" extension

### ISSUE THREAD

**Issue by rik-shaw** [zpydr/gnome-shell-extension-taskbar#91]
Right now when using "Bottom Panel" extension, the hover items (application and window name, also the window preview) are still showing below the panel.  This means they aren't visible at all.

When Taskbar is set to use a bottom panel (a "second panel" just for taskbar) the hover items show correctly above the taskbar.  So I think Taskbar either needs to support a single bottom panel itself (and of course then have the hover items show above it), or give a setting that would allow a user to show the hover items above or below the panel (obviously this doesn't make sense when using a top bar to show the items above it, or when using a bottom bar to show below, but this coding may be easier than making Taskbar itself setup a single bottom bar).

**Comment by lucazade** [comment]
it would be nice to have a bottom panel feature with hover items!

**Comment by zpydr** [comment]
Added support for the "bottom panel" extension.
