### ISSUE TITLE
Gnome-Tweak-Tool Error Loading

### ISSUE THREAD

**Issue by goredefex** [zpydr/gnome-shell-extension-taskbar#94]
I love this extension and it is the only one that comes close to being what I need to work in Gnome for a Taskbar... that being said since my last computer wipe down and rebuild something is not allowing me to use Taskbar anymore. I have tried both the Gnome Extensions official page with the "on/off" switch/button to install and I have also followed your Wiki on how to manually install. Neither allow me to run this extension. 

![image](https://cloud.githubusercontent.com/assets/8227174/12849542/80809cd6-cbf6-11e5-8d34-015e6abdbd04.png)

When I go into tweak tool it shows a caution symbol with the tooltip Error loading extension, on hover. 

![image](https://cloud.githubusercontent.com/assets/8227174/12849448/0e508518-cbf6-11e5-9145-d5f27f25a129.png)

The command gsettings ~get org.gnome.shell enabled-extensions~ (without tildas) shows that this extension is included in the list.

Heres the kicker, sometimes randomly on a reboot I will log on and have the job of having my taskbar back for a session. When I log off or restart its gone again. So... I know it **CAN** work on my system it just refuses to. 

I have also tried turning off all other extensions and rebooting and trying to turn on Taskbar first but it still shows the same message and wont let me turn it on in tweak tool.... help :( I need my taskbar back badly for work.

**Comment by goredefex** [comment]
and as I finished typing that I logged out for lunch and came back into the office quickly to check my mail and low and behold its at the bottom of my screen lol. So.... I logged back off again and logged back in and... no Taskbar :(  

emotional rollercoaster lol

**Comment by zpydr** [comment]
Please open a terminal and paste the following lines to remove TaskBar completely:
`sudo rm -r "/usr/share/gnome-shell/extensions/TaskBar@zpydr/" "$HOME/.local/share/gnome-shell/extensions/TaskBar@zpydr/"`
`dconf reset -f /org/gnome/shell/extensions/TaskBar/`
The first command will remove any TaskBar files, the second will clear all TaskBar settings.
Then restart GNOME Shell with [ Alt ]-[ F2 ] + [ r ], and re-install TaskBar: [Installation Wiki](https://github.com/zpydr/gnome-shell-extension-taskbar/wiki/TaskBar-Installation)
Please let me know if this solved the issue. Thanks

**Comment by atulRanaa** [comment]
Error occurred while upgrading interrupted, Atl + f2 + r , works fine for me, Thank you
