### ISSUE TITLE
task label not refreshed properly

### ISSUE THREAD

**Issue by lucazade** [zpydr/gnome-shell-extension-taskbar#96]
Task label is not refreshed until you open another application.
For example if you open nautilus as first application you can see only "Loading" and not "Home".. same happens for Spotify, you can see "null" then if you open another application the spotify task label is refreshed.
![nautilus1](https://cloud.githubusercontent.com/assets/1557010/13767601/4e7ef8ba-ea6c-11e5-99d3-a153c5be42c9.png)
![refresh](https://cloud.githubusercontent.com/assets/1557010/13767600/4e7df032-ea6c-11e5-8d05-f7f49ea6b917.png)
![spotify1](https://cloud.githubusercontent.com/assets/1557010/13767599/4e7cd990-ea6c-11e5-9c5b-0fdba78c21a7.png)

btw great release with bottom panel and task label support :)

**Comment by lucazade** [comment]
fixed in latest commit

**Comment by zpydr** [comment]
I missed that, thanks a lot.
