### ISSUE TITLE
Main.screenShield is null

### ISSUE THREAD

**Issue by lucazade** [zpydr/gnome-shell-extension-taskbar#97]
I get this error when extension is loading

`mar 15 05:15:18 archos gnome-session[799]: (gnome-shell:891): Gjs-WARNING **: JS ERROR: TypeError: Main.screenShield is null
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.setSystemSignals@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:692
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.enable@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:369
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.onParamChanged@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:295
mar 15 05:15:18 archos gnome-session[799]: loadTheme@resource:///org/gnome/shell/ui/main.js:312
mar 15 05:15:18 archos gnome-session[799]: ThemeManager<._changeTheme@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:65
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 05:15:18 archos gnome-session[799]: ThemeManager<.enable@/usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/extension.js:24
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 05:15:18 archos gnome-session[799]: enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:128
mar 15 05:15:18 archos gnome-session[799]: loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:170
mar 15 05:15:18 archos gnome-session[799]: _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
mar 15 05:15:18 archos gnome-session[799]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 05:15:18 archos gnome-session[799]: ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 05:15:18 archos gnome-session[799]: bind/<@resource:///org/gnome/gjs/modules/lang.js:95
mar 15 05:15:18 archos gnome-session[799]: collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
mar 15 05:15:18 archos gnome-session[799]: ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 05:15:18 archos gnome-session[799]: _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
mar 15 05:15:18 archos gnome-session[799]: enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
mar 15 05:15:18 archos gnome-session[799]: _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
mar 15 05:15:18 archos gnome-session[799]: init@resource:///org/gnome/shell/ui/extensionSystem.js:346
mar 15 05:15:18 archos gnome-session[799]: _initializeUI@resource:///org/gnome/shell/ui/main.js:209
mar 15 05:15:18 archos gnome-session[799]: start@resource:///org/gnome/shell/ui/main.js:120
mar 15 05:15:18 archos gnome-session[799]: @<main>:1
mar 15 05:15:18 archos gnome-session[799]: (gnome-shell:891): Gjs-WARNING **: JS ERROR: Exception in callback for signal: monitors-changed: TypeError: Main.screenShield is null
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.setSystemSignals@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:692
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.enable@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:369
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.onParamChanged@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:295
mar 15 05:15:18 archos gnome-session[799]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 05:15:18 archos gnome-session[799]: LayoutManager<._monitorsChanged@resource:///org/gnome/shell/ui/layout.js:501
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
mar 15 05:15:18 archos gnome-session[799]: (gnome-shell:891): Gjs-WARNING **: JS ERROR: Exception in callback for signal: monitors-changed: TypeError: Main.screenShield is null
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.setSystemSignals@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:692
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.enable@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:369
mar 15 05:15:18 archos gnome-session[799]: TaskBar.prototype.onParamChanged@/home/luca/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:295
mar 15 05:15:18 archos gnome-session[799]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
mar 15 05:15:18 archos gnome-session[799]: LayoutManager<._monitorsChanged@resource:///org/gnome/shell/ui/layout.js:501
mar 15 05:15:18 archos gnome-session[799]: wrapper@resource:///org/gnome/gjs/modules/lang.js:178
`

**Comment by lucazade** [comment]
I think it is related to login manager.. I use lightdm instead of gdm.
I fixed this way..

```
        if (Main.screenShield !== null) {
            this.screenShieldLockId = Main.screenShield.connect('lock-status-changed', Lang.bind(this, this.onParamChanged));
        }
```

**Comment by lucazade** [comment]
fixed in latest commit

**Comment by zpydr** [comment]
Thanks for pointing me to this issue and for providing a solution with it. Great!
